package vista;

import java.awt.*;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
 *    Laboratorio # 3
 *    Profesor: Luis Romo Portilla 
 *
 *    Archivo:  VentanaAfiliadoVista.java
 *    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

public class VentanaAfiliadoVista extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAfiliado
     */

        
    public VentanaAfiliadoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloAfiliado = new javax.swing.JLabel();
        lbl_cedulaAfiliado = new javax.swing.JLabel();
        lbl_nombreAfiliado = new javax.swing.JLabel();
        txtF_cedulaAfiliado = new javax.swing.JTextField();
        txtF_nombreAfiliado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Afiliado = new javax.swing.JTable();
        btn_afiliadoAgregar = new javax.swing.JButton();
        btn_afiliadoActualizar = new javax.swing.JButton();
        btn_afiliadoVerLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl_tituloAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tituloAfiliado.setText("Afiliados");
        getContentPane().add(lbl_tituloAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_cedulaAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_cedulaAfiliado.setText("Cédula");
        getContentPane().add(lbl_cedulaAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        lbl_nombreAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nombreAfiliado.setText("Nombre completo");
        getContentPane().add(lbl_nombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(txtF_cedulaAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, -1));
        getContentPane().add(txtF_nombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, -1));

        table_Afiliado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_Afiliado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 190));

        btn_afiliadoAgregar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_afiliadoAgregar.setText("Agregar");
        getContentPane().add(btn_afiliadoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, -1));

        btn_afiliadoActualizar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_afiliadoActualizar.setText("Actualizar");
        getContentPane().add(btn_afiliadoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btn_afiliadoVerLista.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_afiliadoVerLista.setText("Ver Lista");
        getContentPane().add(btn_afiliadoVerLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAfiliadoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afiliadoActualizar;
    private javax.swing.JButton btn_afiliadoAgregar;
    private javax.swing.JButton btn_afiliadoVerLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cedulaAfiliado;
    private javax.swing.JLabel lbl_nombreAfiliado;
    private javax.swing.JLabel lbl_tituloAfiliado;
    private javax.swing.JTable table_Afiliado;
    private javax.swing.JTextField txtF_cedulaAfiliado;
    private javax.swing.JTextField txtF_nombreAfiliado;
    // End of variables declaration//GEN-END:variables
}
