package vista;

import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
    Laboratorio # 3
    Profesor: Luis Romo Portilla 

    Archivo:  VentanaAfiliadosVista.java
    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

public class VentanaAfiliadosVista extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel();
    
    /**
     * Creates new form ventanaAfiliado
     */  
    public VentanaAfiliadosVista() {
        initComponents();
        table_Afiliados.setModel(modeloTabla);
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloAfiliado = new javax.swing.JLabel();
        lbl_cedulaAfiliado = new javax.swing.JLabel();
        lbl_nombreAfiliado = new javax.swing.JLabel();
        txtF_cedulaAfiliado = new javax.swing.JTextField();
        txtF_nombreAfiliado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Afiliados = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tituloAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tituloAfiliado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloAfiliado.setText("Afiliados");
        jPanel1.add(lbl_tituloAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_cedulaAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_cedulaAfiliado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cedulaAfiliado.setText("Cédula");
        jPanel1.add(lbl_cedulaAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_nombreAfiliado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nombreAfiliado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombreAfiliado.setText("Nombre completo");
        jPanel1.add(lbl_nombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(txtF_cedulaAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, -1));
        jPanel1.add(txtF_nombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 190, -1));

        table_Afiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_Afiliados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 220));

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_agregar.setText("Agregar");
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 90, -1));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_volver.setText("Volver");
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_modificar.setText("Modificar");
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAfiliadosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAfiliadosVista().setVisible(true);
            }
        });
    }

    public String getCedula(){        
        return txtF_cedulaAfiliado.getText();
    }

    public void setTxtF_cedulaAfiliado(JTextField txtF_cedulaAfiliado) {
        this.txtF_cedulaAfiliado = txtF_cedulaAfiliado;
    }

    public boolean getTxtFState(){
        return txtF_nombreAfiliado.getText().isEmpty();
    }
    public String getNombre() {
        return txtF_nombreAfiliado.getText();
    }

    public void setTxtF_nombreAfiliado(JTextField txtF_nombreAfiliado) {
        this.txtF_nombreAfiliado = txtF_nombreAfiliado;
    }
    
    /**
     * Crea los titulos de la tabla 
     */
    public void configurarTabla(){
        String[] titulosTabla = new String[]{"ID", "NOMBRE COMPLETO"};
        modeloTabla.setColumnIdentifiers(titulosTabla);
    }
    
    /**
     * Añade una nueva fila con los datos de un nuevo afiliado
     * @param Id El Id del nuevo afiliado
     * @param nombreCompleto El nombre completo del nuevo afiliado
     */
    public void nuevaFilaAfiliado(int Id, String nombreCompleto){
        modeloTabla.addRow(new Object[]{
            Id, nombreCompleto
        });
    }
    
    /**
     * Elimina todas las filas de la tabla para dejarla vacia
     */
    public void limpiarTabla(){
        int filasTabla = modeloTabla.getRowCount();
        for(int i = 0; i < filasTabla; i++){
            modeloTabla.removeRow(0);
        }
    }
    
    public void limpiarCampos(){
        txtF_cedulaAfiliado.setText("");
        txtF_nombreAfiliado.setText("");
    }
    
    public void cerrar(){
        dispose();
    }
    
    public void addAgregarListener(ActionListener listener){
        btn_agregar.addActionListener(listener);
    }
    
    public void addVolverListener(ActionListener listener){
        btn_volver.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cedulaAfiliado;
    private javax.swing.JLabel lbl_nombreAfiliado;
    private javax.swing.JLabel lbl_tituloAfiliado;
    private javax.swing.JTable table_Afiliados;
    private javax.swing.JTextField txtF_cedulaAfiliado;
    private javax.swing.JTextField txtF_nombreAfiliado;
    // End of variables declaration//GEN-END:variables
}
