package vista;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
    Laboratorio # 3
    Profesor: Luis Romo Portilla 

    Archivo:  VentanaPrincipalVista.java
    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

public class VentanaPrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipalVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_servicios = new javax.swing.JButton();
        btn_especialistas = new javax.swing.JButton();
        btn_afiliado = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        btn_citas = new javax.swing.JButton();
        btn_consultorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 82, -1));

        btn_servicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_servicios.setText("Servicios");
        getContentPane().add(btn_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        btn_especialistas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_especialistas.setText("Especialistas");
        btn_especialistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_especialistasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_especialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        btn_afiliado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_afiliado.setText("Afiliados");
        btn_afiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afiliadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_afiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setText("Servicio de Salud Univalle");
        getContentPane().add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 60));

        btn_citas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_citas.setText("Citas");
        btn_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_citasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        btn_consultorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultorios.setText("Consultorios");
        getContentPane().add(btn_consultorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_afiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_afiliadoActionPerformed

    private void btn_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_citasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_citasActionPerformed

    private void btn_especialistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_especialistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_especialistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afiliado;
    private javax.swing.JButton btn_citas;
    private javax.swing.JButton btn_consultorios;
    private javax.swing.JButton btn_especialistas;
    private javax.swing.JButton btn_servicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
