package vista;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
    Laboratorio # 3
    Profesor: Luis Romo Portilla 

    Archivo:  VentanaServiciosVista.java
    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class VentanaServiciosVista extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel();
    /** Creates new form ventanaServicios */
    public VentanaServiciosVista() {
        initComponents();
        table_servicios.setModel(modeloTabla);
        configurarTabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_serviciosTitulo = new javax.swing.JLabel();
        lbl_nombreServicios = new javax.swing.JLabel();
        txtF_nombreServicios = new javax.swing.JTextField();
        lbl_codigoServicios = new javax.swing.JLabel();
        txtF_idServicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_servicios = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_serviciosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_serviciosTitulo.setText("Servicios");
        jPanel1.add(lbl_serviciosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_nombreServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nombreServicios.setText("Servicios");
        jPanel1.add(lbl_nombreServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        txtF_nombreServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_nombreServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(txtF_nombreServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, -1));

        lbl_codigoServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_codigoServicios.setText("ID Servicio");
        jPanel1.add(lbl_codigoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        jPanel1.add(txtF_idServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        table_servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_servicios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 340, 240));

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_agregar.setText("Agregar");
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_modificar.setText("Modificar");
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_volver.setText("Volver");
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_eliminar.setText("Eliminar");
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtF_nombreServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_nombreServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_nombreServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaServiciosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaServiciosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaServiciosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaServiciosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaServiciosVista().setVisible(true);
            }
        });
    }
    
    public String getNombreServicios(){        
        return txtF_nombreServicios.getText();
    }

    public void setNombreServicios(JTextField txtF_nombreServicios) {
        this.txtF_nombreServicios = txtF_nombreServicios;
    }

    public String getIdServicio() {
        return txtF_idServicio.getText();
    }

    public void setgetIdServicio(JTextField txtF_idServicio) {
        this.txtF_idServicio = txtF_idServicio;
    }

    /**
     * Crea los titulos de la tabla 
     */
    public void configurarTabla(){
        String[] titulosTabla = new String[]{"ID", "SERVICIO"};
        modeloTabla.setColumnIdentifiers(titulosTabla);
    }
    
    /**
     * Añade una nueva fila con el id de un nuevo servicio
     * @param Id El Id del servicio
     * @param nombreServicio El servicio de salud 
     */
    public void nuevaFilaServicio(int Id, String nombreServicio){
        modeloTabla.addRow(new Object[]{
            Id, nombreServicio
        });
    }
    
    /**
     * Elimina todas las filas de la tabla para dejarla vacia
     */
    public void limpiarTabla(){
        int filasTabla = modeloTabla.getRowCount();
        for(int i = 0; i < filasTabla; i++){
            modeloTabla.removeRow(0);
        }
    }
    
    public void limpiarCampos(){
        txtF_nombreServicios.setText("");
        txtF_idServicio.setText("");
    }
    
    public void cerrar(){
        dispose();
    }
    
    public void addAgregarListener(ActionListener listener){
        btn_agregar.addActionListener(listener);
    }
    
    public void addModificarListener(ActionListener listener){
        btn_modificar.addActionListener(listener);
    }
    
    public void addEliminarListener(ActionListener listener){
        btn_eliminar.addActionListener(listener);
    }
    
    public void addVolverListener(ActionListener listener){
        btn_volver.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigoServicios;
    private javax.swing.JLabel lbl_nombreServicios;
    private javax.swing.JLabel lbl_serviciosTitulo;
    private javax.swing.JTable table_servicios;
    private javax.swing.JTextField txtF_idServicio;
    private javax.swing.JTextField txtF_nombreServicios;
    // End of variables declaration//GEN-END:variables

}
