package vista;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
 *    Laboratorio # 3
 *    Profesor: Luis Romo Portilla 
 *
 *    Archivo:  VentanaCitasVista.java
 *    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

public class VentanaCitasVista extends javax.swing.JFrame {

    /** Creates new form ventanaCitas */
    public VentanaCitasVista() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_citas = new javax.swing.JLabel();
        lbl_citasAlifiado = new javax.swing.JLabel();
        txtF_citasAfiliado = new javax.swing.JTextField();
        lbl_citasMedico = new javax.swing.JLabel();
        txtF_citasMedico = new javax.swing.JTextField();
        lbl_citasServicios = new javax.swing.JLabel();
        txtF_citasServicio = new javax.swing.JTextField();
        lbl_citasFecha = new javax.swing.JLabel();
        txtF_citasFecha = new javax.swing.JTextField();
        lbl_citasHora = new javax.swing.JLabel();
        txtF_citasHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_citas = new javax.swing.JTable();
        btn_citasAgregar = new javax.swing.JButton();
        btn_citasActualizar = new javax.swing.JButton();
        btn_citasVerLista = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 385));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_citas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_citas.setText("Citas");
        jPanel1.add(lbl_citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_citasAlifiado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_citasAlifiado.setText("Afiliado");
        jPanel1.add(lbl_citasAlifiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel1.add(txtF_citasAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, -1));

        lbl_citasMedico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_citasMedico.setText("Médico");
        jPanel1.add(lbl_citasMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        jPanel1.add(txtF_citasMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, -1));

        lbl_citasServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_citasServicios.setText("Servicio");
        jPanel1.add(lbl_citasServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        jPanel1.add(txtF_citasServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        lbl_citasFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_citasFecha.setText("Fecha");
        jPanel1.add(lbl_citasFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        jPanel1.add(txtF_citasFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        lbl_citasHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_citasHora.setText("Hora");
        jPanel1.add(lbl_citasHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(txtF_citasHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        table_citas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_citas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 340, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        btn_citasAgregar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_citasAgregar.setText("Agregar");
        getContentPane().add(btn_citasAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        btn_citasActualizar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_citasActualizar.setText("Actualizar");
        getContentPane().add(btn_citasActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        btn_citasVerLista.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_citasVerLista.setText("Ver Lista");
        getContentPane().add(btn_citasVerLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCitasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCitasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCitasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCitasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCitasVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_citasActualizar;
    private javax.swing.JButton btn_citasAgregar;
    private javax.swing.JButton btn_citasVerLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_citas;
    private javax.swing.JLabel lbl_citasAlifiado;
    private javax.swing.JLabel lbl_citasFecha;
    private javax.swing.JLabel lbl_citasHora;
    private javax.swing.JLabel lbl_citasMedico;
    private javax.swing.JLabel lbl_citasServicios;
    private javax.swing.JTable table_citas;
    private javax.swing.JTextField txtF_citasAfiliado;
    private javax.swing.JTextField txtF_citasFecha;
    private javax.swing.JTextField txtF_citasHora;
    private javax.swing.JTextField txtF_citasMedico;
    private javax.swing.JTextField txtF_citasServicio;
    // End of variables declaration//GEN-END:variables

}
