package vista;

import java.awt.event.ActionListener;

/**
 *    Fundamentos de programación orientada a eventos 750014C-01  
    Laboratorio # 3
    Profesor: Luis Romo Portilla 

    Archivo:  VentanaPrincipalVista.java
    Licencia: GNU-GPL 
 *    @version  1.0
 *    
 *    @author   Alejandro Guerrero Cano           (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">}
 *    @author   Estiven Andres Martinez Granados  (202179687-3743) {@literal <"estiven.martinez@correounivalle.edu.co">}
 *    @author   Juan David Loaiza Santiago        (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">}
 * 
*/

public class VentanaPrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipalVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_servicios = new javax.swing.JButton();
        btn_especialistas = new javax.swing.JButton();
        btn_afiliados = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        btn_citas = new javax.swing.JButton();
        btn_consultorios = new javax.swing.JButton();
        lbl_titulo2 = new javax.swing.JLabel();
        btn_restaurarBackup = new javax.swing.JButton();
        btn_exportarAfiliados = new javax.swing.JButton();
        lbl_herramientas = new javax.swing.JLabel();
        lbl_backup = new javax.swing.JLabel();
        btn_realizarBackup = new javax.swing.JButton();
        lbl_gestionar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 301));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_servicios.setBackground(new java.awt.Color(255, 0, 51));
        btn_servicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_servicios.setForeground(new java.awt.Color(255, 255, 255));
        btn_servicios.setText("Servicios");
        jPanel1.add(btn_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, -1));

        btn_especialistas.setBackground(new java.awt.Color(255, 0, 51));
        btn_especialistas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_especialistas.setForeground(new java.awt.Color(255, 255, 255));
        btn_especialistas.setText("Especialistas");
        jPanel1.add(btn_especialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, -1));

        btn_afiliados.setBackground(new java.awt.Color(255, 0, 51));
        btn_afiliados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_afiliados.setForeground(new java.awt.Color(255, 255, 255));
        btn_afiliados.setText("Afiliados");
        jPanel1.add(btn_afiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("   Servicio de Salud Universidad del Valle"); // NOI18N
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 40));

        btn_citas.setBackground(new java.awt.Color(255, 0, 51));
        btn_citas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_citas.setForeground(new java.awt.Color(255, 255, 255));
        btn_citas.setText("Citas");
        jPanel1.add(btn_citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, -1));

        btn_consultorios.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultorios.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultorios.setText("Consultorios");
        jPanel1.add(btn_consultorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));

        lbl_titulo2.setBackground(new java.awt.Color(255, 0, 51));
        lbl_titulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_titulo2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo2.setOpaque(true);
        jPanel1.add(lbl_titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));

        btn_restaurarBackup.setBackground(new java.awt.Color(255, 0, 0));
        btn_restaurarBackup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_restaurarBackup.setForeground(new java.awt.Color(255, 255, 255));
        btn_restaurarBackup.setText("Restaurar Backup");
        jPanel1.add(btn_restaurarBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 160, -1));

        btn_exportarAfiliados.setBackground(new java.awt.Color(255, 0, 0));
        btn_exportarAfiliados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_exportarAfiliados.setForeground(new java.awt.Color(255, 255, 255));
        btn_exportarAfiliados.setText("Exportar afiliados");
        btn_exportarAfiliados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportarAfiliadosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exportarAfiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 160, -1));

        lbl_herramientas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_herramientas.setForeground(new java.awt.Color(0, 0, 0));
        lbl_herramientas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_herramientas.setText("Herramientas");
        jPanel1.add(lbl_herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 110, -1));

        lbl_backup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_backup.setForeground(new java.awt.Color(0, 0, 0));
        lbl_backup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_backup.setText("Copia de seguridad y restauracion");
        jPanel1.add(lbl_backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 260, 20));

        btn_realizarBackup.setBackground(new java.awt.Color(255, 0, 0));
        btn_realizarBackup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_realizarBackup.setForeground(new java.awt.Color(255, 255, 255));
        btn_realizarBackup.setText("Realizar Backup");
        jPanel1.add(btn_realizarBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 160, -1));

        lbl_gestionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_gestionar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_gestionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gestionar.setText("Gestionar");
        jPanel1.add(lbl_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exportarAfiliadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportarAfiliadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exportarAfiliadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalVista().setVisible(true);
            }
        });
    }

    public void addServiciosListener(ActionListener listener){
        btn_servicios.addActionListener(listener);
    }
    public void addEspecialistasListener(ActionListener listener){
        btn_especialistas.addActionListener(listener);
    }
    public void addAfiliadosListener(ActionListener listener){
        btn_afiliados.addActionListener(listener);
    }
    public void addConsultoriosListener(ActionListener listener){
        btn_consultorios.addActionListener(listener);
    }
    public void addCitasListener(ActionListener listener){
        btn_citas.addActionListener(listener);
    }
    public void addExportarAfiliadosListener(ActionListener listener){
        btn_exportarAfiliados.addActionListener(listener);
    }
    public void addRealizarBackupListener(ActionListener listener){
        btn_realizarBackup.addActionListener(listener);
    }
    public void addRestaurarBackupListener(ActionListener listener){
        btn_restaurarBackup.addActionListener(listener);
    }
    
    public void cerrar(){
        dispose();
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afiliados;
    private javax.swing.JButton btn_citas;
    private javax.swing.JButton btn_consultorios;
    private javax.swing.JButton btn_especialistas;
    private javax.swing.JButton btn_exportarAfiliados;
    private javax.swing.JButton btn_realizarBackup;
    private javax.swing.JButton btn_restaurarBackup;
    private javax.swing.JButton btn_servicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_backup;
    private javax.swing.JLabel lbl_gestionar;
    private javax.swing.JLabel lbl_herramientas;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo2;
    // End of variables declaration//GEN-END:variables
}
